


-- -----------------------------------------------------
-- Table `BDEMPLEADO`.`EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS EMPLEADO;
CREATE TABLE EMPLEADO (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(45) NULL,
  APELLIDO VARCHAR(45) NULL,
  EDAD INT NULL,
  FECHANACIMIENTO DATE NULL,
  SALARIO DECIMAL);

-- -----------------------------------------------------
-- Table `BDEMPLEADO`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(50),
DNI CHAR(8),
USUARIO VARCHAR(30),
CLAVE VARCHAR(300),
ROLES VARCHAR(50)
);

INSERT INTO USUARIO(NOMBRE,APELLIDO,DNI,USUARIO,CLAVE,ROLES) VALUES('Francisco','Julca','47467404','admin','dQNjUIMorJb8Ubj2+wVGYp6eAeYkdekqAcnYp+aRq5w=','ROLE_ADMIN');
INSERT INTO USUARIO(NOMBRE,APELLIDO,DNI,USUARIO,CLAVE,ROLES) VALUES('Jose','Sosa','45464547','jsosa','2222','ROLE_USER');
INSERT INTO USUARIO(NOMBRE,APELLIDO,DNI,USUARIO,CLAVE,ROLES) VALUES('Andrea','Guzman','34536454','aguzman','3434','ROLE_USER');


INSERT INTO EMPLEADO (NOMBRE, APELLIDO, EDAD, FECHANACIMIENTO, SALARIO) VALUES ('Francisco', 'Julca Velasquez', '32', '1991-12-05', '5000');
INSERT INTO EMPLEADO (NOMBRE, APELLIDO, EDAD, FECHANACIMIENTO, SALARIO) VALUES ('Sandra', 'Vega Huaman', '30', '1993-10-13', '5000');
INSERT INTO EMPLEADO (NOMBRE, APELLIDO, EDAD, FECHANACIMIENTO, SALARIO) VALUES ('Andrea', 'Sosa Ugarte', '32', '1991-10-15', '5000');



